[package]
name = "RVM"
version = "0.0.2"
edition = "2021"

[dependencies]
bytemuck = "1.13.0"
bytesize = "1.1.0"

winit = "0.27.5"
egui = "0.20.1"
egui_winit_vulkano = "0.22.0"
vulkano = "0.32.3"
vulkano-win = "0.32.0"
vulkano-shaders = "0.32.0"
vulkano-util = "0.32.0"